spring:
  application:
    name: api-kafka-consumer
  kafka:
    consumer:
      bootstrap-servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: MANUAL
    producer:
      bootstrap-servers: my-cluster-kafka-bootstrap.default.svc:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#  data:
#    mongodb:
#      uri: mongodb://adminuser:password123@10.43.246.249:27017/admin
debug: true