apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-consumer-deployment
  annotations:
    commitID: "5286f97c1b1abb74ff62c920b1735651bacdfcd3"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-kafka-consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-consumer
    spec:
      containers:
        - name: api-kafka-consumer
          image: 'xavelo/api-kafka-consumer:5286f97c1b1abb74ff62c920b1735651bacdfcd3'
          ports:
            - containerPort: 80
