apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-consumer-deployment
  annotations:
    commitID: "09bdae4f074f741e9efcc017398d8fa92ad8bd65"
spec:
  # replicas: 2 - to be managed KEDA HPA
  selector:
    matchLabels:
      app: api-kafka-consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-consumer
    spec:
      containers:
        - name: api-kafka-consumer
          image: 'xavelo/api-kafka-consumer:09bdae4f074f741e9efcc017398d8fa92ad8bd65'
          ports:
            - containerPort: 80
