apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-consumer-deployment
  annotations:
    commitID: "2d0380d0b000c6d4cb21bb141de9bf96068e6e3a"
spec:
  # replicas: 2 - to be managed KEDA HPA
  selector:
    matchLabels:
      app: api-kafka-consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-consumer
    spec:
      containers:
        - name: api-kafka-consumer
          image: 'xavelo/api-kafka-consumer:2d0380d0b000c6d4cb21bb141de9bf96068e6e3a'
          ports:
            - containerPort: 80
