apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-consumer-deployment
  annotations:
    commitID: "52b77a5329fe576ec2b3a2904a2b83d9eaf79f3f"
spec:
  replicas: 2s
  selector:
    matchLabels:
      app: api-kafka-consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-consumer
    spec:
      containers:
        - name: api-kafka-consumer
          image: 'xavelo/api-kafka-consumer:52b77a5329fe576ec2b3a2904a2b83d9eaf79f3f'
          ports:
            - containerPort: 80
