apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-template-deployment
  annotations:
    commitID: "b04f46ffaef557536c433aa499699f487e1e3dfa"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-template
    spec:
      containers:
        - name: api-template
          image: 'xavelo/api-template-spring-boot:b04f46ffaef557536c433aa499699f487e1e3dfa'
          ports:
            - containerPort: 80
