apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-consumer-deployment
  annotations:
    commitID: "47c42e3a0c20e64dde0a8e948aa81cb6f0687795"
spec:
  # replicas: 2 - to be managed KEDA HPA
  selector:
    matchLabels:
      app: api-kafka-consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-consumer
    spec:
      containers:
        - name: api-kafka-consumer
          image: 'xavelo/api-kafka-consumer:47c42e3a0c20e64dde0a8e948aa81cb6f0687795'
          ports:
            - containerPort: 80
