apiVersion: v1
kind: Service
metadata:
  name: api-kafka-consumer-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
  selector:
    app: api-kafka-consumer