apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-consumer-deployment
  annotations:
    commitID: "cb2d55dbad3819d2c5d3d71dacd1c31bbc9cff87"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-kafka-consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-consumer
    spec:
      containers:
        - name: api-kafka-consumer
          image: 'xavelo/api-kafka-consumer:cb2d55dbad3819d2c5d3d71dacd1c31bbc9cff87'
          ports:
            - containerPort: 80
