apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-consumer-deployment
  annotations:
    commitID: "ae3c91b2d2009fa37fd7bdb63e5332fb3aab330f"
spec:
  # replicas: 2 - to be managed by HPA
  selector:
    matchLabels:
      app: api-kafka-consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-consumer
    spec:
      containers:
        - name: api-kafka-consumer
          image: 'xavelo/api-kafka-consumer:ae3c91b2d2009fa37fd7bdb63e5332fb3aab330f'
          resources:
            requests:
              cpu: "500m" # Set CPU request to 500m (0.5 CPU core)
              memory: "256Mi" # Optional, set memory request
            limits:
              cpu: "1000m" # Set CPU limit to 1000m (1 CPU core)
              memory: "512Mi" # Optional, set memory limit
          ports:
            - containerPort: 80
