apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-consumer-deployment
  annotations:
    commitID: "d1ca2960b73af5e694a44957947f7b1f19883f96"
spec:
  # replicas: 2 - to be managed KEDA HPA
  selector:
    matchLabels:
      app: api-kafka-consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-consumer
    spec:
      containers:
        - name: api-kafka-consumer
          image: 'xavelo/api-kafka-consumer:d1ca2960b73af5e694a44957947f7b1f19883f96'
          ports:
            - containerPort: 80
