apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-kafka-consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-kafka-consumer-deployment
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 99