apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-kafka-consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-kafka-consumer-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Minimum time to wait before scaling down (default is 300s)
      policies:
        - type: Percent
          value: 50   # Reduce by 50% of current replicas at a time
          periodSeconds: 30  # Check every 30 seconds