apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-consumer-deployment
  annotations:
    commitID: "e35f1838820c2dbcbed3fec47b37bb346ce938b1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-kafka-consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-consumer
    spec:
      containers:
        - name: api-kafka-consumer
          image: 'xavelo/api-kafka-consumer:e35f1838820c2dbcbed3fec47b37bb346ce938b1'
          ports:
            - containerPort: 80
