apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  commit_id: dfdfdfdsf
  timestamp: '2024-05-25T19:56:30+0200'
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world-k3s
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: xavelo/hello-world-k3s:latest
          ports:
            - containerPort: 80
