apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "842b7e099b020d4f1c4222719ac1651659da8077"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-k3s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: xavelo/hello-world-k3s:${GITHUB_SHA}
          ports:
            - containerPort: 80
