apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "b79443b4099d99a2979addd8e568d0c78a39272c"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-k3s
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: xavelo/hello-world-k3s:latest
          ports:
            - containerPort: 80
