apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "39d1454095fd20d1036db09661c4003665930a6a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-k3s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: 'xavelo/hello-world-k3s:39d1454095fd20d1036db09661c4003665930a6a'
          ports:
            - containerPort: 80
