apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "d1dbf4f61b881b1ee1827d735a3c32c33696e39b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-k3s
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: xavelo/hello-world-k3s:latest
          ports:
            - containerPort: 80
