apiVersion: v1
kind: Service
metadata:
  name: hello-world-k3s-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: hello-world-k3s