apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "772bcbc1a0e541ce2872cf5f9b8bbfa859a28df4"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world-k3s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: 'xavelo/hello-world-k3s:772bcbc1a0e541ce2872cf5f9b8bbfa859a28df4'
          ports:
            - containerPort: 80
