apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "2b4be4f0ecb2dcf17e55320f40c4afdfe825593e"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-world-k3s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: 'xavelo/hello-world-k3s:2b4be4f0ecb2dcf17e55320f40c4afdfe825593e'
          ports:
            - containerPort: 80
