apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "5f01c7d579723d7e31c1c7e3a8645cb681485b8e"
spec:
  replicas: 50
  selector:
    matchLabels:
      app: hello-world-k3s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: 'xavelo/hello-world-k3s:5f01c7d579723d7e31c1c7e3a8645cb681485b8e'
          ports:
            - containerPort: 80
