apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "2dc1ec950e0530877893cc7818f8568f3ef0fe50"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-k3s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: 'xavelo/hello-world-k3s:2dc1ec950e0530877893cc7818f8568f3ef0fe50'
          ports:
            - containerPort: 80
