apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "976f47186f39ff4b05993e38cf32ccdb4a089d04"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-k3s
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: xavelo/hello-world-k3s:latest
          ports:
            - containerPort: 80
